# This is a basic workflow to help you get started with Actions

name: snowflake-devops-demo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - 'migrations/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  # This workflow contains a single job called "build"
  deploy-snowflake-changes-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Runs a single command using the runners shell
      - run: echo Hello, world!
      # Runs a set of commands using the runners shell
      - uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x
      # Run schemachange 
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SNOWFLAKE_AUTHENTICATOR: ${{ secrets.AUTHENTICATOR }}
      - run: python --version
      - name: "Step 1 Install schemachange" 
        run: pip install schemachange
      - name: "Step 2 Running schemachange" 
        run: schemachange deploy -f $GITHUB_WORKSPACE/migrations -a $env.SF_ACCOUNT -u $env.SF_USERNAME -r $env.SF_ROLE -w $env.SF_WAREHOUSE -d $env.SF_DATABASE -c $env.SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY
        
        
        
